### ISSUE TITLE
yarn dev failed

### ISSUE THREAD

**Issue by ZhaoTim** [alexcarpenter/alexcarpenter.me#85]
Hi, I love the website ! 
However, when i run `yarn dev`, visit the `localhost:3000`, something wrong.
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/30540533/173629055-7722d0f6-59fb-4c1d-8294-e5d64eac2825.png">

**Comment by alexcarpenter** [comment]
Hey @ZhaoTim, sorry about that. I don't use yarn, so i'd recommend using npm if you'd like to run the website locally.
